"""celery tables

Revision ID: 5bb640ffa66d
Revises: d11980659657
Create Date: 2019-08-06 22:38:07.149303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb640ffa66d'
down_revision = 'd11980659657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_celery_schedules_email', table_name='celery_schedules')
    op.drop_table('celery_schedules')
    op.drop_table('celery_crontabs')
    op.drop_table('celery_intervals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_intervals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('every', sa.INTEGER(), nullable=False),
    sa.Column('period', sa.VARCHAR(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celery_crontabs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('minute', sa.VARCHAR(length=64), nullable=True),
    sa.Column('hour', sa.VARCHAR(length=64), nullable=True),
    sa.Column('day_of_week', sa.VARCHAR(length=64), nullable=True),
    sa.Column('day_of_month', sa.VARCHAR(length=64), nullable=True),
    sa.Column('month_of_year', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celery_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('task', sa.VARCHAR(length=255), nullable=True),
    sa.Column('interval_id', sa.INTEGER(), nullable=True),
    sa.Column('crontab_id', sa.INTEGER(), nullable=True),
    sa.Column('ldap_user', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('notify', sa.BOOLEAN(), nullable=True),
    sa.Column('arguments', sa.VARCHAR(length=255), nullable=True),
    sa.Column('keyword_arguments', sa.VARCHAR(length=255), nullable=True),
    sa.Column('queue', sa.VARCHAR(length=255), nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=255), nullable=True),
    sa.Column('routing_key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('last_run_at', sa.DATETIME(), nullable=True),
    sa.Column('total_run_count', sa.INTEGER(), nullable=True),
    sa.Column('date_changed', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('enabled IN (0, 1)'),
    sa.CheckConstraint('notify IN (0, 1)'),
    sa.ForeignKeyConstraint(['crontab_id'], ['celery_crontabs.id'], ),
    sa.ForeignKeyConstraint(['interval_id'], ['celery_intervals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_celery_schedules_email', 'celery_schedules', ['email'], unique=False)
    # ### end Alembic commands ###
