"""Create all tables - initial commit

Revision ID: d11980659657
Revises: 
Create Date: 2019-07-26 17:53:53.992729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11980659657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminusers_username'), 'adminusers', ['username'], unique=True)
    op.create_table('apiusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('ldap_user', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiusers_email'), 'apiusers', ['email'], unique=False)
    op.create_index(op.f('ix_apiusers_username'), 'apiusers', ['username'], unique=True)
    op.create_table('celery_crontabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.String(length=64), nullable=True),
    sa.Column('hour', sa.String(length=64), nullable=True),
    sa.Column('day_of_week', sa.String(length=64), nullable=True),
    sa.Column('day_of_month', sa.String(length=64), nullable=True),
    sa.Column('month_of_year', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celery_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('every', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_completed', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('logfile', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runhistory_user'), 'runhistory', ['user'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dn', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dn')
    )
    op.create_table('celery_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task', sa.String(length=255), nullable=True),
    sa.Column('interval_id', sa.Integer(), nullable=True),
    sa.Column('crontab_id', sa.Integer(), nullable=True),
    sa.Column('ldap_user', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('arguments', sa.String(length=255), nullable=True),
    sa.Column('keyword_arguments', sa.String(length=255), nullable=True),
    sa.Column('queue', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=255), nullable=True),
    sa.Column('routing_key', sa.String(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('total_run_count', sa.Integer(), nullable=True),
    sa.Column('date_changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crontab_id'], ['celery_crontabs.id'], ),
    sa.ForeignKeyConstraint(['interval_id'], ['celery_intervals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_celery_schedules_email'), 'celery_schedules', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_celery_schedules_email'), table_name='celery_schedules')
    op.drop_table('celery_schedules')
    op.drop_table('user')
    op.drop_index(op.f('ix_runhistory_user'), table_name='runhistory')
    op.drop_table('runhistory')
    op.drop_table('celery_intervals')
    op.drop_table('celery_crontabs')
    op.drop_index(op.f('ix_apiusers_username'), table_name='apiusers')
    op.drop_index(op.f('ix_apiusers_email'), table_name='apiusers')
    op.drop_table('apiusers')
    op.drop_index(op.f('ix_adminusers_username'), table_name='adminusers')
    op.drop_table('adminusers')
    # ### end Alembic commands ###
